import ftfy, re
with open('templates/heart-beat/index.html', 'r', encoding='utf-8') as f:
    text = f.read()
fixed = ftfy.fix_text(text)
matches = re.findall(r'<title>(.*?)</title>', fixed)
print('Title:', repr(matches[0]) if matches else None)
matches = re.findall(r'name="description" content="(.*?)"', fixed)
print('Description:', repr(matches[0]) if matches else None)
matches = re.findall(r'name="keywords" content="(.*?)"', fixed)
print('Keywords:', repr(matches[0]) if matches else None)
matches = re.findall(r'<div class="hl-title">(.*?)</div>', fixed)
print('Title2:', repr(matches[0]) if matches else None)
matches = re.findall(r'<p class="card-greeting">(.*?)</p>', fixed)
print('Greeting:', repr(matches[0]) if matches else None)
matches = re.findall(r'<p class="card-ending">(.*?)</p>', fixed)
print('Ending:', repr(matches[0]) if matches else None)
matches = re.findall(r'aria-label="(.*?)"', fixed)
print('Aria:', repr(matches[0]) if matches else None)
